
version: "3.3"

services:
  tada_notebook:
    build:
      context: .
    # To use a different port of host, change the first 8888.
    ports:
      - "8888:8888"
    volumes:
      - type: "bind"
        source: ./
        target: /notebooks
